@startwbs
'https://plantuml.com/wbs-diagram

+ TSDB Instance(Top Leave)
++ Catalog(database)
+++ schema
++++ table
+++++ Time series
++++++ Tags
++++++ Field
++++ Index
++++ View
++++ function
@endwbs