@startjson
{
	"chunkIndex": [{
		"id": "int",
		"chunkHeadOffset": "long",
		"statistics": {
			"max": "list<max<DataType>>",
			"min": "list<min<DataType>>",
			"sum": "list<sum<DataType>>",
			"count": "list<count<DataType>>",
			"first": "list<DataType>",
			"last": "list<DataType>",
			"startTime": "long",
			"endTime": "long",
			"mbr": "binary"
		}
	}],
	"timeSeriesIndex":[ {
		"id": "int",
		"chunkIndexSizeList": "List<long>",
		"chunkIndexOffsetList": "List<long>"
	}],
	"timeSeriesIndexOffset": [{
		"id": "int",
		"offset": "long",
		"size": "int"
	}, {
		"...": "..."
	}],

	"bloomFilter": "binary"
}
@endjson